"""add document batch_id

Revision ID: 277b6dc3ae47
Revises: 5bca9ba118e9
Create Date: 2026-08-02 19:12:59.115943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277b6dc3ae47'
down_revision: Union[str, Sequence[str], None] = '5bca9ba118e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('batch_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_documents_batch_id'), 'documents', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_batch_id'), table_name='documents')
    op.drop_column('documents', 'batch_id')
    # ### end Alembic commands ###
