"""add document total_amount and currency

Revision ID: 2cb6cd0c9e90
Revises: b7c1be51a1e5
Create Date: 2026-08-07 17:05:37.892168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb6cd0c9e90'
down_revision: Union[str, Sequence[str], None] = 'b7c1be51a1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('documents', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'currency')
    op.drop_column('documents', 'total_amount')
    # ### end Alembic commands ###
