"""add vendors and expense categories

Revision ID: 5bca9ba118e9
Revises: 9c0d0b54474c
Create Date: 2026-07-14 13:26:41.468229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bca9ba118e9'
down_revision: Union[str, Sequence[str], None] = '9c0d0b54474c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_expense_categories_company_id_name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_vendors_company_id_name')
    )
    op.add_column('documents', sa.Column('vendor_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('expense_category_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_documents_vendor_id_vendors', 'documents', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_documents_expense_category_id_expense_categories', 'documents', 'expense_categories', ['expense_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_expense_category_id_expense_categories', 'documents', type_='foreignkey')
    op.drop_constraint('fk_documents_vendor_id_vendors', 'documents', type_='foreignkey')
    op.drop_column('documents', 'expense_category_id')
    op.drop_column('documents', 'vendor_id')
    op.drop_table('vendors')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
