"""add document_date

Revision ID: b7c1be51a1e5
Revises: 277b6dc3ae47
Create Date: 2026-08-05 10:08:08.087494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c1be51a1e5'
down_revision: Union[str, Sequence[str], None] = '277b6dc3ae47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_documents_document_date'), 'documents', ['document_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_document_date'), table_name='documents')
    op.drop_column('documents', 'document_date')
    # ### end Alembic commands ###
